### DISCUSSION TITLE
Should nesting same name blocks be allowed?

### DISCUSSION THREAD

**Discussion by Intregrisist** [getbem/getbem.github.io#259] [Q&A]
So I was having a conversation with a colleague and I stated that we should not be nesting a BEM block within itself because it can cause CSS selector nightmare.  Below I will show a simple example:

```html
<div class="foo foo--blue">
  <div class="foo foo--red">
    <span class="foo__text">Hello World</span>
  </div>
</div>
```

```postcss
.foo {
  .text {
    .foo--red & {
      color: red;
    }
    .foo--blue & {
      color: blue;
    }
  }
}
```

This is a very small and hopefully clear example.  What color would `.foo__text` get?  I can't find any guide that suggests or argues with nesting same named blocks.

**Comment by iamstarkov** [comment]
I think you are right, it causes unexpected and not desired complexity

**Comment by jednano** [comment]
I think when you expect nesting like this you have to be more specific, using the [`>` combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_selectors):
```scss
.foo {
    &__text {
        .foo--red > & {
            color: red;
        }
        .foo--blue > & {
            color: blue;
        }
    }
}
```
