### DISCUSSION TITLE
BEM in lists

### DISCUSSION THREAD

**Discussion by alfupe** [getbem/getbem.github.io#266] [Q&A]
Let's say we have a very simple block:

``` html
<ul class="list-unstyled">
    <li>one</li>
    <li>two</li>
    <li>...</li>
    <li>ten</li>
</ul>
```

So the css could be:

``` css
.list-unstyled {
    padding-left: 0;
    list-style: none;
}
```

But, what should be done if we would like to let some padding to every single list item? I suppose that according to the BEM good practices should be something like:

``` css
<ul class="list-unstyled">
    <li class="list-unstyled__item">one</li>
    <li class="list-unstyled__item">two</li>
    <li class="list-unstyled__item">...</li>
    <li class="list-unstyled__item">ten</li>
</ul>
```

So the css should be:

``` css
.list-unstyled {
    padding-left: 0;
    list-style: none;
}

.list-unstyled__item {
    padding-bottom: 10px;
}
```

My questions are: Is it so dangerous to add a modifier to the block and style the `<li>` directly? for instance:

``` html
<ul class="list-unstyled list-unstyled--roomy">
    <li>one</li>
    <li>two</li>
    <li>...</li>
    <li>ten</li>
</ul>
```

And then:

``` css
.list-unstyled {
    padding-left: 0;
    list-style: none;
}

.list-unstyled--roomy li {
    padding-bottom: 10px;
}
```

Is it necessary to add the `class="list-unstyled__item"`? Do not you think that's excessive?

Thanks
