### DISCUSSION TITLE
Block Element Modifier - Element Modifier

### DISCUSSION THREAD

**Discussion by TomS-** [getbem/getbem.github.io#273] [Q&A]
I was wondering what would happen in the following instance. I couldn't seem to find an example anywhere. Also I've noticed the last two issues haven't been answered in over a month, is this still active? 

``` html
<div class="intro">
    <span class="intro__span--title"></span>
    <span class="intro__span"></span>
    <span class="intro__span"></span>
</div>
```

``` css
.intro__span { display: block; }
.intro__span--title { font-size: 1.1em; }
```

Now the intro__span--title doesn't take on intro__span so do you have to do `<span class="intro__span intro__span--title"></span>`
