### ISSUE TITLE
Inconsistent statements in docs

### ISSUE THREAD

**Issue by tgelu** [getbem/getbem.github.io#302]
On [https://getbem.com/naming/](https://getbem.com/naming/) we read:

> Block names may consist of Latin letters, digits, and dashes.

But the first and most prominent example in the frontpage contains:

```css
.opinions_box { // <-- contradicts the previous statement
    margin: 0 0 8px 0;
    text-align: center;

    &__view-more {
        text-decoration: underline;
    }

    &__text-input {
        border: 1px solid #ccc;
    }

    &--is-inactive {
        color: gray;
    }
}
```

If a block name may contain letters, digits and dashes it may NOT contain anything else, including an underscore.

I don't know where a change should be made, but I think it should be corrected :)

Cheers
